apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-app
  namespace: expenses-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-app
  template:
    metadata:
      labels:
        app: expenses-app
    spec:
      containers:
      - name: expenses-app
        image: gangwarnishant/expenses-tracker-app:v2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: expense-config
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: expense-config
              key: username         
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: expense-secret
              key: password

        
---

apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: expenses-tracker
spec:
  type: NodePort
  selector:
    app: expenses-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
